name: CI build

on:
  push:
    branches: [ '**' ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macOS-10.15
        cmake_opts: [ "" ]
        arch: [ x86_64 ]
        toolchain: [ default.cmake ]

        include:
          - os: windows-latest
            cmake_opts: -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\install
            toolchain: default.cmake
            arch: x86_64

          - os: ubuntu-18.04
            install: crossbuild-essential-armhf
            toolchain: Linux-arm.cmake
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
            arch: arm

          - os: ubuntu-18.04
            install: crossbuild-essential-arm64
            toolchain: Linux-arm64.cmake
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
            arch: arm64

    steps:
      - name: checkout workspace
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: make build dir
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: install toolchain
        if: ${{ matrix.install != null }}
        run: |
          sudo apt -y update
          sudo apt -y install ${{ matrix.install }}

      - name: install libsystemd if Ubuntu
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt -y update
          sudo apt -y install libsystemd-dev

      - name: configure cmake
        run: cmake ${{matrix.cmake_opts}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/toolchains/${{matrix.toolchain}} -S ${{ github.workspace }} -B ${{github.workspace}}/build

      - name: build ziti-edge-tunnel bundle target
        run: cmake --build ${{github.workspace}}/build --target bundle --verbose

      - name: list bundle artifacts
        run: ls -R
        working-directory: ${{ github.workspace }}/build/bundle/

      - name: list program artifacts
        run: ls -R
        working-directory: ${{ github.workspace }}/build/programs/ziti-edge-tunnel/

      - name: upload bundle artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}
          path: |
            ./build/bundle/ziti-edge-tunnel-*.zip
          if-no-files-found: error
