name: mattermost-ziti-webhook
on: 
  create:
  delete:
  issues:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  pull_request:
  push:
  fork:
  release:

jobs:
  mattermost-ziti-webhook:
    runs-on: macos-latest
    name: POST Webhook
    steps:
    - uses: openziti/ziti-webhook-action@main
      env:
        ZITI_MATTERMOST_IDENTITY: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
      if: ${{ github.actor!= 'dependabot[bot]' && github.repository_owner == 'openziti' && github.event_name != 'pull_request' && env.ZITI_MATTERMOST_IDENTITY != null }}
      with:
        ziti-id: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhook-url: ${{ secrets.ZITI_MATTERMOST_WEBHOOK_URL }}
        webhook-secret: ${{ secrets.ZITI_MATTERMOSTI_WEBHOOK_SECRET }}
